//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Discount_calculation
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.TextBox txtPrice;
    protected global::System.Web.UI.WebControls.TextBox txtDiscount;
    protected global::System.Web.UI.WebControls.Button btnCalculate;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.Label lblResult;
}
